routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});
Auth::routes(['register' => false]);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/print', 'HomeController@print_invoice')->name('print');
    Route::get('/profile', 'HomeController@profile')->name('profile');
    Route::post('/profile', 'HomeController@update_profile')->name('profile');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/cost', 'HomeController@make_new_cost')->name('cost');
    Route::get('/cost', 'HomeController@cost')->name('cost');
    Route::get('/cost/{cost_id}/edit', 'HomeController@cost_update_view')->name('cost_edit');
    Route::post('/cost/{cost_id}/edit', 'HomeController@update_cost')->name('cost_edit');
    Route::get('/cost/{cost_id}/delete', 'HomeController@delete_cost')->name('cost_delete');
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/fourth', 'CustomersController@get_customer_fourth')->name('fourth');
        Route::get('/add', 'CustomersController@new_customer_view')->name('add');
        Route::post('/add', 'CustomersController@make_new_customer');
        Route::get('/search', 'CustomersController@search_customer')->name('search');
        Route::get('/', 'CustomersController@get_user_list')->name('list');
        Route::get('/{user_id}', 'CustomersController@get_user_profile')->name('profile');
        Route::get('/edit/{user_id}', 'CustomersController@get_user_update')->name('edit');
        Route::post('/edit/{user_id}', 'CustomersController@update_user')->name('edit');
        Route::get('/delete/{user_id}', 'CustomersController@delete_user')->name('delete');
    });
    Route::group(['prefix' => 'loan', 'as' => 'loan.'], function () {
        Route::get('/add', 'LoanController@new_loan_view')->name('add');
        Route::post('/add', 'LoanController@make_new_loan');
        Route::get('/', 'LoanController@get_loan_list')->name('list');
        Route::get('/{user_id}', 'LoanController@get_user_profile')->name('profile');
        Route::get('/edit/{loan_id}', 'LoanController@get_loan_update_view')->name('edit');
        Route::post('/edit/{loan_id}', 'LoanController@update_loan')->name('edit');
        Route::get('/delete/{loan_id}', 'LoanController@delete_loan')->name('delete');
        Route::get('/print/{loan_id}', 'LoanController@print_loan')->name('print');

    });
    Route::group(['prefix' => 'installment', 'as' => 'installment.'], function () {
        Route::get('/add', 'InstallmentController@new_installment_view')->name('add');
        Route::post('/add', 'InstallmentController@make_new_installment');
        Route::get('/', 'InstallmentController@get_installment_list')->name('list');
        Route::get('/{user_id}', 'InstallmentController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'InstallmentController@get_installment_update_view')->name('edit');
        Route::post('/edit/{installment_id}', 'InstallmentController@update_installment')->name('edit');
        Route::get('/delete/{installment_id}', 'InstallmentController@delete_installment')->name('delete');
        Route::get('/print/{installment_id}', 'InstallmentController@print_installment')->name('print');
    });
    Route::group(['prefix' => 'sale', 'as' => 'sale.'], function () {
        Route::get('/add', 'SaleController@new_sell_view')->name('add');
        Route::post('/add', 'SaleController@make_new_sell');
        Route::get('/', 'SaleController@get_sale_list')->name('list');
        Route::get('/{user_id}', 'SaleController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'SaleController@get_sale_update_view')->name('edit');
        Route::get('/print/{sell_id}', 'SaleController@get_sale_print_view')->name('print');
        Route::post('/edit/{installment_id}', 'SaleController@update_sale')->name('edit');
        Route::get('/delete/{installment_id}', 'SaleController@delete_sale')->name('delete');
    });
    Route::group(['prefix' => 'deposit', 'as' => 'deposit.'], function () {
        Route::get('/add', 'DepositController@new_deposit_view')->name('add');
        Route::post('/add', 'DepositController@make_new_deposit');
        Route::get('/', 'DepositController@get_deposit_list')->name('list');
        Route::get('/{user_id}', 'DepositController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'DepositController@get_deposit_update_view')->name('edit');
        Route::post('/edit/{installment_id}', 'DepositController@update_deposit')->name('edit');
        Route::get('/delete/{installment_id}', 'DepositController@delete_deposit')->name('delete');
        Route::get('/print/{installment_id}', 'DepositController@print_deposit')->name('print');
    });
    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/others/cost', 'ReportController@get_others_cost_report_view')->name('other_costs');
        Route::post('/others/cost', 'ReportController@get_others_cost_report')->name('other_costs');
        Route::post('/others/cost/print', 'ReportController@print_others_cost_report')->name('other_costs_print');
        Route::get('/users', 'ReportController@get_all_user_report')->name('users');
        Route::post('/users', 'ReportController@print_all_user_report')->name('users');
        Route::get('/user/loan', 'ReportController@get_user_loan_report_view')->name('user_loan');
        Route::post('/user/loan', 'ReportController@get_user_loan_report')->name('user_loan');
        Route::post('/user/loan/print', 'ReportController@print_user_loan_report')->name('user_loan_print');
        Route::get('/user/sale', 'ReportController@get_user_sale_report_view')->name('user_sale');
        Route::post('/user/sale', 'ReportController@get_user_sale_report')->name('user_sale');
        Route::post('/user/sale/print', 'ReportController@print_user_sale_report')->name('user_sale_print');
        Route::get('/user/deposit', 'ReportController@get_user_deposit_report_view')->name('user_deposit');
        Route::post('/user/deposit', 'ReportController@get_user_deposit_report')->name('user_deposit');
        Route::post('/user/deposit/print', 'ReportController@print_user_deposit_report')->name('user_deposit_print');
        Route::get('/user/individual/transaction', 'ReportController@get_user_individual_transaction_report_view')->name('individual_transaction');
        Route::post('/user/individual/transaction', 'ReportController@get_user_individual_transaction_report')->name('individual_transaction');
        Route::post('/user/individual/transaction/print', 'ReportController@print_user_individual_transaction_report')->name('individual_transaction_print');
    });
});

app/Models/Deposit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Deposit extends Model
{
    protected $fillable = ["deposit_uid","customer_id","deposit","date","note"];

    public function customer(){
        return $this->hasOne(Customer::class,'id','customer_id');
    }
}

app/Http/Controllers/DepositController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\DepositsDataTable;
use App\Http\Requests\NewDepositRequest;
use App\Models\Deposit;
use App\Models\Installment;
use App\Models\Sale;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class DepositController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function new_deposit_view()
    {
        return view('deposit.new_deposit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param NewDepositRequest $request
     * @return RedirectResponse
     */
    public function make_new_deposit(NewDepositRequest $request)
    {
        try {
            Deposit::create([
                "deposit_uid" => uniqid(),
                "customer_id" => $request->input('customer_id'),
                "deposit" => $request->input('deposit'),
                "date" => $request->input('date'),
                "note" => $request->input('note')
            ]);
            return redirect()->back()->with("message", "Deposit create successfully done");
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors("Deposit create failed");
        }
    }

    /**
     * Display the specified resource.
     * @param DepositsDataTable $dataTable
     * @return mixed
     */
    public function get_deposit_list(DepositsDataTable $dataTable)
    {
        return $dataTable->render('deposit.deposits');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $deposit_id
     * @return View
     */
    public function get_deposit_update_view($deposit_id)
    {
        $deposit = Deposit::with('customer')->where(['deposit_uid'=>$deposit_id])->first();

        $sell_amount = Sale::where(['customer_id' => $deposit->customer->id])->sum('sell');
        $installment_amount = Installment::where(['customer_id' => $deposit->customer->id])->sum('taka');
        $commission_amount = Sale::where(['customer_id' => $deposit->customer->id])->sum('commission');
        $spend_amount = Sale::where(['customer_id' => $deposit->customer->id])->sum('other_spend');
        $fourth = $sell_amount - $commission_amount - $spend_amount-$installment_amount;
        $previous_payment = Deposit::where(["customer_id" =>$deposit->customer->id])->sum('deposit');
        return view('deposit.edit_deposit',['deposit'=>$deposit,'fourth'=>$fourth,'previous_payment'=>$previous_payment]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param NewDepositRequest $request
     * @param $deposit_id
     * @return RedirectResponse
     */
    public function update_deposit(NewDepositRequest $request,$deposit_id)
    {
        $deposit = Deposit::where(['id'=>$deposit_id])->first();
        try {
            $deposit->update([
                "customer_id" => $request->input('customer_id'),
                "deposit" => $request->input('deposit'),
                "date" => $request->input('date'),
                "note" => $request->input('note')
            ]);
            return redirect()->back()->with("message", "Deposit update successfully done");
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors("Deposit update failed");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $deposit_id
     * @return RedirectResponse
     */
    public function delete_deposit($deposit_id)
    {
        $deposit = Deposit::where(['deposit_uid'=>$deposit_id])->first();
        $deposit->delete();
        return redirect()->back()->with("message", "Deposit delete success");
    }

    public function print_deposit($deposit_id){
        $deposit = Deposit::with('customer')->where(['deposit_uid'=>$deposit_id])->first();
        return view('deposit.print',['deposit'=>$deposit]);
    }
}

resources/views/deposit/deposits.blade.php
@extends('layouts.master')
@section("style")
    <link rel="stylesheet" type="text/css" href="{{asset('plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset("plugins/table/datatable/custom_dt_html5.css")}}">
    <link rel="stylesheet" type="text/css" href="{{asset("plugins/table/datatable/dt-global_style.css")}}">
@endsection
@section('heading')
    <h3>সকল জমার প্রদানর হিসাব-নিকাশের তালিকা</h3>
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('home')}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="feather feather-home">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
            </a>
        </li>
        <li class="breadcrumb-item"><a href="{{route('deposit.add')}}">জমার</a></li>
        <li class="breadcrumb-item active" aria-current="page"><span>আমানত/ কিস্তি লিস্ট</span></li>
    </ol>
@endsection
@section('content')
    <div class="row layout-top-spacing" id="cancel-row">
        <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
            <div class="widget-content widget-content-area br-6">
                <div class="table-responsive mb-4 mt-4">
                    {{$dataTable->table(['class'=>"table table-hover non-hover","style"=>"width:100%"])}}
                </div>
            </div>
        </div>
    </div>
@endsection
@section("script")
    <!-- BEGIN PAGE LEVEL CUSTOM SCRIPTS -->
    <script src="{{asset('plugins/table/datatable/datatables.js')}}"></script>
    <!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
    <script src="{{asset('plugins/table/datatable/button-ext/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/jszip.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/buttons.html5.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/buttons.print.min.js')}}"></script>
    {{$dataTable->scripts()}}
@endsection

resources/views/deposit/edit_deposit.blade.php
@extends('layouts.master')
@section('style')
    <link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('plugins/flatpickr/flatpickr.css')}}">
    <style>
        .select2-container {
            margin-bottom: 0 !important;
        }
    </style>
@endsection
@section('heading')
    <h3>নতুন জমার প্রদানর হিসাব</h3>
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('home')}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="feather feather-home">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
            </a>
        </li>
        <li class="breadcrumb-item"><a href="javascript:void(0);">জমার</a></li>
        <li class="breadcrumb-item active" aria-current="page"><span>নতুন জমার  প্রদানর হিসাব</span></li>
    </ol>
@endsection
@section('content')
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-12 layout-spacing">
            <div class="widget-content-area br-4">
                <form method="post" action="{{route('deposit.edit',$deposit->id)}}">
                    @csrf
                    <div class="form-row mb-4">
                        <div class="form-group col-md-3">
                            <label for="customer_id">ব্যক্তির নাম</label>
                            <select name="customer_id" id="customer_id" class="form-control">
                                <option value="{{$deposit->customer->id}}">{{$deposit->customer->name}} ({{$deposit->customer->phone}})</option>
                            </select>
                        </div>
                        <div class="form-group col-md-3">
                            <label for="fourth">মোট পাকা চৌঠা </label>
                            <input type="number" class="form-control" id="fourth" value="{{$fourth}}" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label for="previous_payment">আগে টাকা প্রদান করা হয়েছিল</label>
                            <input type="number" class="form-control" id="previous_payment" name="previous_payment" value="{{$previous_payment}}" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label for="due_payment">আর বাকি আছে</label>
                            <input type="number" class="form-control" id="due_payment" name="due_payment" value="{{$fourth-$previous_payment}}" readonly>
                        </div>

                    </div>
                    <div class="form-row mb-4">
                        <div class="form-group col-md-6 mb-0">
                            <label for="date">তারিখ</label>
                            <input value="{{$deposit->date}}" name="date" id="date"
                                   class="form-control flatpickr flatpickr-input active" type="text"
                                   placeholder="তারিখ নির্বাচন করুন ..">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="deposit">আমানত/ কিস্তি টাকার পরিমান</label>
                            <input type="number" name="deposit" class="form-control" id="deposit" value="{{$deposit->deposit}}">
                        </div>
                    </div>
                    <div class="form-row mb-4">
                        <div class="form-group col-md-12">
                            <label for="note">নোট</label>
                            <input name="note" type="text" class="form-control" id="note" value="{{$deposit->note}}">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">তথ্য যুক্ত করুন</button>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('plugins/select2/select2.min.js')}}"></script>
    <script src="{{asset("plugins/flatpickr/flatpickr.js")}}"></script>
    <script src="{{asset("plugins/axios/dist/axios.js")}}"></script>
    <script>
        var f1 = flatpickr(document.getElementById('date'));

        $("#customer_id").select2({
            placeholder: "Select Customer",
            ajax: {
                url: '{{route('users.search')}}',
                dataType: 'json',
                data: function (params) {
                    // Query parameters will be ?search=[term]&type=public
                    return {
                        search: params.term,
                        type: "public"
                    };
                },
                processResults: function (response) {
                    return {
                        results: $.map(response.data, function (txt, val) {
                            return {id: txt.id, text: txt.name}
                        })
                    };
                }
                // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
            }
        });

        $('#sell').on('keypress keyup blur change', function (e) {
            var sell = $(this).val();
            var commission = '{{env('COMMISION')}}';
            const calculation = sell * (commission / 100);
            $("#commission").val(calculation);
        });
        $('#customer_id').on('change', function (e) {
            var customer_id = $(this).val();
            axios.get(`{{route('users.fourth')}}?customer_id=${customer_id}`)
                .then(function (response) {
                    $("#fourth").val(response.data.fourth);
                    $("#previous_payment").val(response.data.previous_payment);
                    $("#due_payment").val(response.data.fourth-response.data.previous_payment);
                })
                .catch(function (error) {
                    console.log(error.response);
                });
        });
    </script>
@endsection

resources/views/deposit/new_deposit.blade.php
@extends('layouts.master')
@section('style')
    <link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('plugins/flatpickr/flatpickr.css')}}">
    <style>
        .select2-container {
            margin-bottom: 0 !important;
        }
    </style>
@endsection
@section('heading')
    <h3>নতুন জমার প্রদানর হিসাব</h3>
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('home')}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="feather feather-home">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
            </a>
        </li>
        <li class="breadcrumb-item"><a href="javascript:void(0);">জমার</a></li>
        <li class="breadcrumb-item active" aria-current="page"><span>নতুন জমার  প্রদানর হিসাব</span></li>
    </ol>
@endsection
@section('content')
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-12 layout-spacing">
            <div class="widget-content-area br-4">
                <form method="post" action="{{route('deposit.add')}}">
                    @csrf
                    <div class="form-row mb-4">
                        <div class="form-group col-md-3">
                            <label for="customer_id">ব্যক্তির নাম</label>
                            <select name="customer_id" id="customer_id" class="form-control">
                                <option selected>ব্যক্তির নাম নির্বাচন করুন</option>
                            </select>
                        </div>
                        <div class="form-group col-md-3">
                            <label for="fourth">মোট পাকা চৌঠা </label>
                            <input type="number" class="form-control" id="fourth" placeholder="৬০,০০০" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label for="previous_payment">আগে টাকা প্রদান করা হয়েছিল</label>
                            <input type="number" class="form-control" id="previous_payment" name="previous_payment"
                                   placeholder="৫০,০০০" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label for="due_payment">আর বাকি আছে</label>
                            <input type="number" class="form-control" id="due_payment" name="due_payment" placeholder="১০,০০০" readonly>
                        </div>
                    </div>
                    <div class="form-row mb-4">
                        <div class="form-group col-md-6 mb-0">
                            <label for="date">তারিখ</label>
                            <input value="{{date('Y-m-d')}}" name="date" id="date"
                                   class="form-control flatpickr flatpickr-input active" type="text"
                                   placeholder="তারিখ নির্বাচন করুন ..">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="deposit">নগদ জমা</label>
                            <input type="number" name="deposit" class="form-control" id="deposit" placeholder="৬০,০০০">
                        </div>

                    </div>
                    <div class="form-row mb-4">
                        <div class="form-group col-md-12">
                            <label for="note">নোট</label>
                            <input name="note" type="text" class="form-control" id="note" placeholder="নোট">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">তথ্য যুক্ত করুন</button>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('plugins/select2/select2.min.js')}}"></script>
    <script src="{{asset("plugins/flatpickr/flatpickr.js")}}"></script>
    <script src="{{asset("plugins/axios/dist/axios.js")}}"></script>
    <script>
        var f1 = flatpickr(document.getElementById('date'));

        $("#customer_id").select2({
            placeholder: "Select Customer",
            ajax: {
                url: '{{route('users.search')}}',
                dataType: 'json',
                data: function (params) {
                    // Query parameters will be ?search=[term]&type=public
                    return {
                        search: params.term,
                        type: "public"
                    };
                },
                processResults: function (response) {
                    return {
                        results: $.map(response.data, function (txt, val) {
                            return {id: txt.id, text: txt.name}
                        })
                    };
                }
                // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
            }
        });

        $('#sell').on('keypress keyup blur change', function (e) {
            var sell = $(this).val();
            var commission = '{{env('COMMISION')}}';
            const calculation = sell * (commission / 100);
            $("#commission").val(calculation);
        });
        $('#customer_id').on('change', function (e) {
            var customer_id = $(this).val();
            axios.get(`{{route('users.fourth')}}?customer_id=${customer_id}`)
                .then(function (response) {
                    $("#fourth").val(response.data.fourth);
                    $("#previous_payment").val(response.data.previous_payment);
                    $("#due_payment").val(response.data.fourth-response.data.previous_payment);
                })
                .catch(function (error) {
                    console.log(error.response);
                });
        });
    </script>
@endsection

resources/views/deposit/print.blade.php
@extends('layouts.invoice')

@section('customer_section')
    <p class="inv-customer-name">{{$deposit->customer->name}}</p>
    <p class="inv-customer-name">{{$deposit->customer->company}}</p>
    <p class="inv-street-addr">{{$deposit->customer->address}}</p>
@endsection
@section("invoice_head")
    ভাউচার
@endsection
@section('invoice_no')
    {{banglaNumber($deposit->id)}}{{banglaNumber($deposit->customer->id)}}{{banglaNumber(date('md',strtotime($deposit->created_at)))}}
@endsection

@section('invoice_date')
    {{banglaNumber($deposit->date)}}
@endsection

@section('content')
    <table class="table">
        <thead class="">
        <tr>
            <th class="text-left" scope="col">ক্রঃ নং</th>
            <th class="text-center" scope="col">বিবরণ</th>
            <th class="text-right" scope="col">জমা টাকার পরিমান</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="text-left">{{banglaNumber(1)}}</td>
            <td class="text-center">{{$deposit->note}}</td>
            <td class="text-right">{{en2bnNumber($deposit->deposit)}}</td>
        </tr>
        </tbody>
    </table>
@endsection
@section('content_footer')
    <div class="row">
        <div class="col-sm-8 col-7 grand-total-title">
            <h5 class="">সর্বমোট জমা: </h5>
        </div>
        <div class="col-sm-4 col-5 grand-total-amount">
            <h5 class="">{{en2bnNumber($deposit->deposit)}} টাকা</h5>
        </div>
    </div>
@endsection