routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});
Auth::routes(['register' => false]);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/print', 'HomeController@print_invoice')->name('print');
    Route::get('/profile', 'HomeController@profile')->name('profile');
    Route::post('/profile', 'HomeController@update_profile')->name('profile');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/cost', 'HomeController@make_new_cost')->name('cost');
    Route::get('/cost', 'HomeController@cost')->name('cost');
    Route::get('/cost/{cost_id}/edit', 'HomeController@cost_update_view')->name('cost_edit');
    Route::post('/cost/{cost_id}/edit', 'HomeController@update_cost')->name('cost_edit');
    Route::get('/cost/{cost_id}/delete', 'HomeController@delete_cost')->name('cost_delete');
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/fourth', 'CustomersController@get_customer_fourth')->name('fourth');
        Route::get('/add', 'CustomersController@new_customer_view')->name('add');
        Route::post('/add', 'CustomersController@make_new_customer');
        Route::get('/search', 'CustomersController@search_customer')->name('search');
        Route::get('/', 'CustomersController@get_user_list')->name('list');
        Route::get('/{user_id}', 'CustomersController@get_user_profile')->name('profile');
        Route::get('/edit/{user_id}', 'CustomersController@get_user_update')->name('edit');
        Route::post('/edit/{user_id}', 'CustomersController@update_user')->name('edit');
        Route::get('/delete/{user_id}', 'CustomersController@delete_user')->name('delete');
    });
    Route::group(['prefix' => 'loan', 'as' => 'loan.'], function () {
        Route::get('/add', 'LoanController@new_loan_view')->name('add');
        Route::post('/add', 'LoanController@make_new_loan');
        Route::get('/', 'LoanController@get_loan_list')->name('list');
        Route::get('/{user_id}', 'LoanController@get_user_profile')->name('profile');
        Route::get('/edit/{loan_id}', 'LoanController@get_loan_update_view')->name('edit');
        Route::post('/edit/{loan_id}', 'LoanController@update_loan')->name('edit');
        Route::get('/delete/{loan_id}', 'LoanController@delete_loan')->name('delete');
        Route::get('/print/{loan_id}', 'LoanController@print_loan')->name('print');

    });
    Route::group(['prefix' => 'installment', 'as' => 'installment.'], function () {
        Route::get('/add', 'InstallmentController@new_installment_view')->name('add');
        Route::post('/add', 'InstallmentController@make_new_installment');
        Route::get('/', 'InstallmentController@get_installment_list')->name('list');
        Route::get('/{user_id}', 'InstallmentController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'InstallmentController@get_installment_update_view')->name('edit');
        Route::post('/edit/{installment_id}', 'InstallmentController@update_installment')->name('edit');
        Route::get('/delete/{installment_id}', 'InstallmentController@delete_installment')->name('delete');
        Route::get('/print/{installment_id}', 'InstallmentController@print_installment')->name('print');
    });
    Route::group(['prefix' => 'sale', 'as' => 'sale.'], function () {
        Route::get('/add', 'SaleController@new_sell_view')->name('add');
        Route::post('/add', 'SaleController@make_new_sell');
        Route::get('/', 'SaleController@get_sale_list')->name('list');
        Route::get('/{user_id}', 'SaleController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'SaleController@get_sale_update_view')->name('edit');
        Route::get('/print/{sell_id}', 'SaleController@get_sale_print_view')->name('print');
        Route::post('/edit/{installment_id}', 'SaleController@update_sale')->name('edit');
        Route::get('/delete/{installment_id}', 'SaleController@delete_sale')->name('delete');
    });
    Route::group(['prefix' => 'deposit', 'as' => 'deposit.'], function () {
        Route::get('/add', 'DepositController@new_deposit_view')->name('add');
        Route::post('/add', 'DepositController@make_new_deposit');
        Route::get('/', 'DepositController@get_deposit_list')->name('list');
        Route::get('/{user_id}', 'DepositController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'DepositController@get_deposit_update_view')->name('edit');
        Route::post('/edit/{installment_id}', 'DepositController@update_deposit')->name('edit');
        Route::get('/delete/{installment_id}', 'DepositController@delete_deposit')->name('delete');
        Route::get('/print/{installment_id}', 'DepositController@print_deposit')->name('print');
    });
    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/others/cost', 'ReportController@get_others_cost_report_view')->name('other_costs');
        Route::post('/others/cost', 'ReportController@get_others_cost_report')->name('other_costs');
        Route::post('/others/cost/print', 'ReportController@print_others_cost_report')->name('other_costs_print');
        Route::get('/users', 'ReportController@get_all_user_report')->name('users');
        Route::post('/users', 'ReportController@print_all_user_report')->name('users');
        Route::get('/user/loan', 'ReportController@get_user_loan_report_view')->name('user_loan');
        Route::post('/user/loan', 'ReportController@get_user_loan_report')->name('user_loan');
        Route::post('/user/loan/print', 'ReportController@print_user_loan_report')->name('user_loan_print');
        Route::get('/user/sale', 'ReportController@get_user_sale_report_view')->name('user_sale');
        Route::post('/user/sale', 'ReportController@get_user_sale_report')->name('user_sale');
        Route::post('/user/sale/print', 'ReportController@print_user_sale_report')->name('user_sale_print');
        Route::get('/user/deposit', 'ReportController@get_user_deposit_report_view')->name('user_deposit');
        Route::post('/user/deposit', 'ReportController@get_user_deposit_report')->name('user_deposit');
        Route::post('/user/deposit/print', 'ReportController@print_user_deposit_report')->name('user_deposit_print');
        Route::get('/user/individual/transaction', 'ReportController@get_user_individual_transaction_report_view')->name('individual_transaction');
        Route::post('/user/individual/transaction', 'ReportController@get_user_individual_transaction_report')->name('individual_transaction');
        Route::post('/user/individual/transaction/print', 'ReportController@print_user_individual_transaction_report')->name('individual_transaction_print');
    });
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
class Customer extends Model implements HasMedia
{
    use HasMediaTrait;
    protected $fillable = ["name", "date_of_birth", "company", "father", "mother", "email", "phone", "address", "permanent_address","loan"];
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\CustomersDataTable;
use App\Http\Requests\CustomerUpdateRequest;
use App\Http\Requests\NewCustomerRequest;
use App\Models\Customer;
use App\Models\Deposit;
use App\Models\Installment;
use App\Models\Loan;
use App\Models\Sale;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class CustomersController extends Controller
{
    /**
     * Display a user/customer list .
     *
     * @param CustomersDataTable $dataTable
     * @return Application|Factory|View
     */
    public function get_user_list(CustomersDataTable $dataTable)
    {
        return $dataTable->render("customer.customers");
    }

    /**
     * Display a new customer form view .
     *
     * @return Application|Factory|View
     */
    public function new_customer_view()
    {
        return view("customer.new_customer");
    }

    /**
     * Make new customer.
     *
     * @param NewCustomerRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function make_new_customer(NewCustomerRequest $request)
    {
        DB::beginTransaction();
        try {
            $customer = Customer::create([
                "name" => $request->input("name"),
                "date_of_birth" => $request->input("dob"),
                "company" => $request->input("company"),
                "father" => $request->input("father"),
                "mother" => $request->input("mother"),
                "email" => $request->input("email"),
                "phone" => $request->input("phone"),
                "address" => $request->input("address"),
                "permanent_address" => $request->input("permanent_address")
            ]);
            add_media_file($customer, $request->file("profile"), config("const.media.profile"));
            add_media_file($customer, $request->file("nid_card"), config("const.media.nid_card"));
            add_media_file($customer, $request->file("check"), config("const.media.check"));
            DB::commit();
            return redirect()->back()->with("message", "User add successfully done");
        } catch (\Exception $exception) {
            DB::rollBack();
            return redirect()->back()->withErrors("Users added failed");
        }
    }

    /**
     * Get customer profile
     *
     * @param $customer_id
     * @return Application|Factory|View
     */
    public function get_user_profile($customer_id)
    {
        $customer = Customer::where(['id' => $customer_id])->first();
        if ($customer){
        $deposit = Deposit::where(['customer_id' => $customer_id])->sum('deposit');
        $deposits = Deposit::where(['customer_id' => $customer_id])->get();
        $loan = Loan::where(['customer_id' => $customer_id])->sum('taka');
        $loans = Loan::where(['customer_id' => $customer_id])->get();
        $installment = Installment::where(['customer_id' => $customer_id])->sum('taka');
        $installments = Installment::with('transaction')->where(['customer_id' => $customer_id])->get();
        $sale = Sale::where(['customer_id' => $customer_id])->sum('sell');
        $commission = Sale::where(['customer_id' => $customer_id])->sum('commission');
        $other_spend = Sale::where(['customer_id' => $customer_id])->sum('other_spend');
        $tea_spend = Sale::where(['customer_id' => $customer_id])->sum('tea_spend');
        $tax = Sale::where(['customer_id' => $customer_id])->sum('tax');
        $ghat = Sale::where(['customer_id' => $customer_id])->sum('ghat');
        $association = Sale::where(['customer_id' => $customer_id])->sum('association');
        $mosque = Sale::where(['customer_id' => $customer_id])->sum('mosque');
        $fourth = $sale-$commission-$other_spend-$installment-$ghat-$association-$mosque-$tax;
        return view('customer.profile',['mosque'=>$mosque,'association'=>$association,'ghat'=>$ghat,'tax'=>$tax,'deposits'=>$deposits,'installments'=>$installments,'loans'=>$loans,'tea_spend'=>$tea_spend,'other_spend'=>$other_spend,'commission'=>$commission,'sale'=>$sale,'installment'=>$installment,'loan'=>$loan,'deposit'=>$deposit,'customer'=>$customer,'fourth'=>$fourth]);
        }else{
            return redirect()->route('users.list')->withErrors(["Customer not found"]);
        }
    }

    /**
     * Get customer profile update view
     *
     * @param $user_id
     * @return Application|Factory|View
     */
    public function get_user_update($user_id)
    {
        $customer = Customer::where(['id' => $user_id])->first();
        return view('customer.edit_customer', ['customer' => $customer]);
    }

    /**
     * Get customer profile update view
     *
     * @param $user_id
     * @param CustomerUpdateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update_user($user_id, CustomerUpdateRequest $request)
    {
        if ($user_id === $request->input('user_id')):
            DB::beginTransaction();
            try {
                $customer = Customer::where(['id' => $user_id])->first();
                $customer->update([
                    "name" => $request->input("name"),
                    "date_of_birth" => $request->input("dob"),
                    "company" => $request->input("company"),
                    "father" => $request->input("father"),
                    "mother" => $request->input("mother"),
                    "email" => $request->input("email"),
                    "phone" => $request->input("phone"),
                    "address" => $request->input("address"),
                    "permanent_address" => $request->input("permanent_address")
                ]);
                if ($request->hasFile('profile')) {
                    sync_media_file($customer, $request->file("profile"), config("const.media.profile"));
                }
                if ($request->hasFile('nid_card')) {
                    sync_media_file($customer, $request->file("nid_card"), config("const.media.nid_card"));
                }
                if ($request->hasFile('check')) {
                    sync_media_file($customer, $request->file("check"), config("const.media.check"));
                }
                DB::commit();
                return redirect()->back()->with("message", "User update successfully done");
            } catch (\Exception $exception) {
                DB::rollBack();
                return redirect()->back()->withErrors("Users update failed");
            }
        else:
            return redirect()->back()->withErrors("Users update failed");
        endif;
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Customer $customers
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete_user($customer_id)
    {
        try {
            Customer::where(['id' => $customer_id])->first()->delete();
            return redirect()->back()->with("message", "User delete successfully done");
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors("Users delete failed");
        }

    }

    public function search_customer(Request $request)
    {
        try {
            $string = $request->input('search', '');
            $response = Customer::where('name', 'like', "%$string%")
                ->orWhere('company', 'like', "%$string%")
                ->orWhere('phone', 'like', "%$string%")
                ->orWhere('email', 'like', "%$string%")
                ->orWhere('address', 'like', "%$string%")
                ->orWhere('permanent_address', 'like', "%$string%")
                ->get();
            $customers = [];
            foreach ($response as $customer) {
                $customers[] = [
                    'id' => $customer->id,
                    'name' => $customer->name . " (" . $customer->phone . ")",
                ];
            }
            return response()->json(['total' => $response->count(), 'data' => $customers]);
        } catch (\Exception $exception) {
            return response()->json(['message' => $exception->getMessage()], 500);
        }
    }

    public function get_customer_fourth(Request $request)
    {
        $customer_id = $request->input('customer_id');
        $installment_amount = Installment::where(['customer_id' => $customer_id])->sum('taka');
        $sell_amount = Sale::where(['customer_id' => $customer_id])->sum('sell');
        $commission_amount = Sale::where(['customer_id' => $customer_id])->sum('commission');
        $spend_amount = Sale::where(['customer_id' => $customer_id])->sum('other_spend');
        $fourth = $sell_amount - $commission_amount - $spend_amount-$installment_amount;
        $previous_payment = Deposit::where(["customer_id" => $request->input('customer_id')])->sum('deposit');
        return response()->json(['fourth' => $fourth,'previous_payment'=>$previous_payment]);
    }
}

resources/views/customer/customers.blade.php
@extends("layouts.master")
@section("style")
    <link rel="stylesheet" type="text/css" href="{{asset('plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset("plugins/table/datatable/custom_dt_html5.css")}}">
    <link rel="stylesheet" type="text/css" href="{{asset("plugins/table/datatable/dt-global_style.css")}}">
@endsection
@section('heading')
    <h3>ব্যক্তির লিস্ট</h3>
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg></a></li>
        <li class="breadcrumb-item"><a href="{{route("users.add")}}">ব্যক্তি</a></li>
        <li class="breadcrumb-item active" aria-current="page"><span>ব্যক্তির লিস্ট</span></li>
    </ol>
@endsection
@section('content')
    <div class="row">

        <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
            <div class="widget-content widget-content-area br-6">
                <div class="table-responsive mb-4 mt-4">
                    {{$dataTable->table(['class'=>"table table-hover non-hover","style"=>"width:100%"])}}
                </div>
            </div>
        </div>
    </div>
@endsection
@section("script")

    <!-- BEGIN PAGE LEVEL CUSTOM SCRIPTS -->
    <script src="{{asset('plugins/table/datatable/datatables.js')}}"></script>
    <!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
    <script src="{{asset('plugins/table/datatable/button-ext/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/jszip.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/buttons.html5.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/buttons.print.min.js')}}"></script>
    {{$dataTable->scripts()}}
    </script>
@endsection

resources/views/customer/edit_customer.blade.php
@extends("layouts.master")
@section("style")
    <link rel="stylesheet" href="{{asset("plugins/dropify/dropify.min.js")}}">
    <link rel="stylesheet" href="{{asset("plugins/flatpickr/flatpickr.css")}}">
@endsection
@section('heading')
    <h3>এডিট ব্যক্তি</h3>
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('home')}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
            </a>
        </li>
        <li class="breadcrumb-item"><a href="javascript:void(0);">ব্যক্তি </a></li>
        <li class="breadcrumb-item active" aria-current="page"><span>এডিট ব্যক্তি</span></li>
    </ol>
@endsection
@section('content')
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 layout-spacing">
            <form action="{{route("users.edit",['user_id'=>$customer->id])}}" method="post" id="general-info" class="section general-info" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="user_id" value="{{$customer->id}}">
                <div class="info">
                    <div class="row">
                        <div class="col-lg-11 mx-auto">
                            <div class="row">
                                <div class="col-xl-2 col-lg-12 col-md-4">
                                    <div class="upload mt-4 pr-md-4">
                                        <input name="profile" type="file" id="input-file-max-fs" class="dropify" data-default-file="{{get_media_file($customer,config('const.media.profile'))}}" data-max-file-size="2M" />
                                        <p class="mt-2"><i class="flaticon-cloud-upload mr-1"></i> আপলোড ছবি</p>
                                    </div>
                                </div>
                                <div class="col-xl-10 col-lg-12 col-md-8 mt-md-0 mt-4">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="name">ব্যক্তি পুরো নাম</label>
                                                <input value="{{$customer->name}}" name="name" type="text" class="form-control mb-4" id="name" placeholder="Full Name" />
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <label for="dob" class="dob-input">জন্ম তারিখ</label>
                                            <div class="d-sm-flex d-block">
                                                <div class="form-group mr-1">
                                                    <input type="text" value="{{$customer->date_of_birth}}" class="form-control mb-4" id="dob" name="dob" placeholder="YYYY-MM-DD" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="company"> প্রতিষ্ঠানের</label>
                                        <input value="{{$customer->company}}" name="company" type="text" class="form-control mb-4" id="company" placeholder="মেসার্স মা মরিয়ম ফিশিং " />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="father">বাবার নাম</label>
                                        <input value="{{$customer->father}}" name="father" type="text" class="form-control mb-4" id="father" placeholder="ব্যক্তি  বাবার নাম এখানে লিখুন"  />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="mother">মায়ের নাম</label>
                                        <input value="{{$customer->mother}}" type="text" class="form-control mb-4" name="mother" id="mother" placeholder="ব্যক্তি  মায়ের নাম এখানে লিখুন" />
                                    </div>
                                </div>
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="email">ইমেইল</label>
                                        <input name="email" type="text" class="form-control mb-4" id="email" placeholder=" ইমেল এখানে লিখুন" value="{{$customer->email}}" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="phone">ফোন</label>
                                        <input name="phone" type="text" class="form-control mb-4" id="phone" placeholder="ফোন নম্বর এখানে লিখুন" value="{{$customer->phone}}" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="address"> বর্তমান ঠিকানা</label>
                                        <input value="{{$customer->address}}" name="address" type="text" class="form-control mb-4" id="address" placeholder="বর্তমান ঠিকানা এখানে লিখুন" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="permanent_address">স্থায়ী ঠিকানা</label>
                                        <input value="{{$customer->permanent_address}}" name="permanent_address" type="text" class="form-control mb-4" id="permanent_address" placeholder="স্থায়ী ঠিকানা এখানে লিখুন" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="upload mt-4 pr-md-4">
                                        <input name="nid_card" type="file" id="input-file-NIDCard" class="dropify" data-default-file="{{get_media_file($customer,config('const.media.nid_card'))}}" data-max-file-size="2M" />
                                        <p class="mt-2"><i class="flaticon-cloud-upload mr-1"></i> এন আই ডি কার্ড আপলোড </p>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="upload mt-4 pr-md-4">
                                        <input name="check" type="file" id="input-file-CheckCopy" class="dropify" data-default-file="{{get_media_file($customer,config('const.media.check'))}}" data-max-file-size="2M" />
                                        <p class="mt-2"><i class="flaticon-cloud-upload mr-1"></i> চেক এর স্ক্যান কপি আপলোড </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12  mt-4 text-center">
                            <button type="submit" id="multiple-messages" class="btn btn-primary">Save Changes</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection
@section("script")
    <script src="{{asset("plugins/dropify/dropify.min.js")}}"></script>
    <script src="{{asset("plugins/flatpickr/flatpickr.js")}}"></script>
    <script>
        $('.dropify').dropify();
        var f1 = flatpickr(document.getElementById('dob'));
    </script>
@endsection