routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});
Auth::routes(['register' => false]);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/print', 'HomeController@print_invoice')->name('print');
    Route::get('/profile', 'HomeController@profile')->name('profile');
    Route::post('/profile', 'HomeController@update_profile')->name('profile');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/cost', 'HomeController@make_new_cost')->name('cost');
    Route::get('/cost', 'HomeController@cost')->name('cost');
    Route::get('/cost/{cost_id}/edit', 'HomeController@cost_update_view')->name('cost_edit');
    Route::post('/cost/{cost_id}/edit', 'HomeController@update_cost')->name('cost_edit');
    Route::get('/cost/{cost_id}/delete', 'HomeController@delete_cost')->name('cost_delete');
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/fourth', 'CustomersController@get_customer_fourth')->name('fourth');
        Route::get('/add', 'CustomersController@new_customer_view')->name('add');
        Route::post('/add', 'CustomersController@make_new_customer');
        Route::get('/search', 'CustomersController@search_customer')->name('search');
        Route::get('/', 'CustomersController@get_user_list')->name('list');
        Route::get('/{user_id}', 'CustomersController@get_user_profile')->name('profile');
        Route::get('/edit/{user_id}', 'CustomersController@get_user_update')->name('edit');
        Route::post('/edit/{user_id}', 'CustomersController@update_user')->name('edit');
        Route::get('/delete/{user_id}', 'CustomersController@delete_user')->name('delete');
    });
    Route::group(['prefix' => 'loan', 'as' => 'loan.'], function () {
        Route::get('/add', 'LoanController@new_loan_view')->name('add');
        Route::post('/add', 'LoanController@make_new_loan');
        Route::get('/', 'LoanController@get_loan_list')->name('list');
        Route::get('/{user_id}', 'LoanController@get_user_profile')->name('profile');
        Route::get('/edit/{loan_id}', 'LoanController@get_loan_update_view')->name('edit');
        Route::post('/edit/{loan_id}', 'LoanController@update_loan')->name('edit');
        Route::get('/delete/{loan_id}', 'LoanController@delete_loan')->name('delete');
        Route::get('/print/{loan_id}', 'LoanController@print_loan')->name('print');

    });
    Route::group(['prefix' => 'installment', 'as' => 'installment.'], function () {
        Route::get('/add', 'InstallmentController@new_installment_view')->name('add');
        Route::post('/add', 'InstallmentController@make_new_installment');
        Route::get('/', 'InstallmentController@get_installment_list')->name('list');
        Route::get('/{user_id}', 'InstallmentController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'InstallmentController@get_installment_update_view')->name('edit');
        Route::post('/edit/{installment_id}', 'InstallmentController@update_installment')->name('edit');
        Route::get('/delete/{installment_id}', 'InstallmentController@delete_installment')->name('delete');
        Route::get('/print/{installment_id}', 'InstallmentController@print_installment')->name('print');
    });
    Route::group(['prefix' => 'sale', 'as' => 'sale.'], function () {
        Route::get('/add', 'SaleController@new_sell_view')->name('add');
        Route::post('/add', 'SaleController@make_new_sell');
        Route::get('/', 'SaleController@get_sale_list')->name('list');
        Route::get('/{user_id}', 'SaleController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'SaleController@get_sale_update_view')->name('edit');
        Route::get('/print/{sell_id}', 'SaleController@get_sale_print_view')->name('print');
        Route::post('/edit/{installment_id}', 'SaleController@update_sale')->name('edit');
        Route::get('/delete/{installment_id}', 'SaleController@delete_sale')->name('delete');
    });
    Route::group(['prefix' => 'deposit', 'as' => 'deposit.'], function () {
        Route::get('/add', 'DepositController@new_deposit_view')->name('add');
        Route::post('/add', 'DepositController@make_new_deposit');
        Route::get('/', 'DepositController@get_deposit_list')->name('list');
        Route::get('/{user_id}', 'DepositController@get_user_profile')->name('profile');
        Route::get('/edit/{installment_id}', 'DepositController@get_deposit_update_view')->name('edit');
        Route::post('/edit/{installment_id}', 'DepositController@update_deposit')->name('edit');
        Route::get('/delete/{installment_id}', 'DepositController@delete_deposit')->name('delete');
        Route::get('/print/{installment_id}', 'DepositController@print_deposit')->name('print');
    });
    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/others/cost', 'ReportController@get_others_cost_report_view')->name('other_costs');
        Route::post('/others/cost', 'ReportController@get_others_cost_report')->name('other_costs');
        Route::post('/others/cost/print', 'ReportController@print_others_cost_report')->name('other_costs_print');
        Route::get('/users', 'ReportController@get_all_user_report')->name('users');
        Route::post('/users', 'ReportController@print_all_user_report')->name('users');
        Route::get('/user/loan', 'ReportController@get_user_loan_report_view')->name('user_loan');
        Route::post('/user/loan', 'ReportController@get_user_loan_report')->name('user_loan');
        Route::post('/user/loan/print', 'ReportController@print_user_loan_report')->name('user_loan_print');
        Route::get('/user/sale', 'ReportController@get_user_sale_report_view')->name('user_sale');
        Route::post('/user/sale', 'ReportController@get_user_sale_report')->name('user_sale');
        Route::post('/user/sale/print', 'ReportController@print_user_sale_report')->name('user_sale_print');
        Route::get('/user/deposit', 'ReportController@get_user_deposit_report_view')->name('user_deposit');
        Route::post('/user/deposit', 'ReportController@get_user_deposit_report')->name('user_deposit');
        Route::post('/user/deposit/print', 'ReportController@print_user_deposit_report')->name('user_deposit_print');
        Route::get('/user/individual/transaction', 'ReportController@get_user_individual_transaction_report_view')->name('individual_transaction');
        Route::post('/user/individual/transaction', 'ReportController@get_user_individual_transaction_report')->name('individual_transaction');
        Route::post('/user/individual/transaction/print', 'ReportController@print_user_individual_transaction_report')->name('individual_transaction_print');
    });
});

app/Models/Installment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Installment extends Model
{
    protected $fillable = ["installment_uid","customer_id","taka","date","note","added_by"];

    public function customer(){
        return $this->hasOne(Customer::class,'id','customer_id');
    }
    /**
     * Get all of the transactions.
     */
    public function transaction()
    {
        return $this->morphOne(Transaction::class, 'transable',"trans_type","trans_id");
    }
}

app/Http/Controllers/InstallmentController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\InstallmentsDataTable;
use App\Http\Requests\NewInstallmentRequest;
use App\Models\Customer;
use App\Models\Installment;
use App\Models\Loan;
use App\Models\Transaction;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class InstallmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function new_installment_view()
    {
        return view('installment.new_installment');
    }


    /**
     * Store a newly created Installment in storage.
     *
     * @param NewInstallmentRequest $request
     * @return RedirectResponse
     */
    public function make_new_installment(NewInstallmentRequest $request)
    {
        DB::beginTransaction();
        try {
            $installment = Installment::create([
                "installment_uid" => uniqid(),
                "customer_id" => $request->input('customer_id'),
                "taka" => $request->input('taka'),
                "date" => $request->input('date'),
                "note" => $request->input('note'),
                "added_by" => auth()->id()
            ]);
            $customer = Customer::where(['id' => $request->input('customer_id')])->first();
            $customer->decrement('loan', $request->input('taka'));
            $transaction = new Transaction(['trans_calculation' => $customer->loan]);
            $installment->transaction()->save($transaction);
            DB::commit();
            return redirect()->back()->with("message", "New installment create success");
        } catch (\Exception $exception) {
            DB::rollBack();
            dd($exception->getMessage());
            return redirect()->back()->withErrors("New installment create failed");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param InstallmentsDataTable $dataTable
     * @return Response
     */
    public function get_installment_list(InstallmentsDataTable $dataTable)
    {
        return $dataTable->render('installment.installments');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $installment_uid
     * @return View
     */
    public function get_installment_update_view($installment_uid)
    {
        $installment = Installment::with('customer')->where(['installment_uid' => $installment_uid])->first();
        return view('installment.edit_installment', ['installment' => $installment]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param $installment_uid
     * @return RedirectResponse
     */
    public function update_installment(NewInstallmentRequest $request, $installment_uid)
    {
        DB::beginTransaction();
        try {
            $installment = Installment::with('transaction')->where(['installment_uid' => $installment_uid])->first();
            $prev_installment = $installment->taka;
            $customer_id = $request->input('customer_id');
            $diff = $prev_installment - $request->input('taka');
            $installment->update([
                "customer_id" => $customer_id,
                "taka" => $request->input('taka'),
                "date" => $request->input('date'),
                "note" => $request->input('note'),
                "added_by" => auth()->id()
            ]);
            Customer::where(['id' => $request->input('customer_id')])->increment('loan', $diff);
            $installment->transaction()->increment('trans_calculation', $diff);
            $Installments = Installment::with('transaction')
                ->where(['customer_id' => $customer_id])
                ->where('id', '>', $installment->id)
                ->get();
            foreach ($Installments as $cs_installment) {
                $cs_installment->transaction()->increment('trans_calculation', $diff);
            }
            DB::commit();
            return redirect()->back()->with("message", "Installment update success");
        } catch (\Exception $exception) {
            DB::rollBack();
            return redirect()->back()->withErrors("Installment update failed");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $installment_uid
     * @return RedirectResponse
     */
    public function delete_installment($installment_uid)
    {
        DB::beginTransaction();
        try {
            $installment = Installment::with('transaction')->where(['installment_uid' => $installment_uid])->first();
            Customer::where(['id' => $installment->customer_id])->increment('loan', $installment->taka);
            $installments = Installment::with('transaction')
                ->where(['customer_id' => $installment->customer_id])
                ->where('id', '>', $installment->id)
                ->get();
            foreach ($installments as $cs_installment) {
                $cs_installment->transaction()->increment('trans_calculation', $installment->taka);
            }
            $installment->transaction->delete();
            $installment->delete();
            DB::commit();
            return redirect()->back()->with("message", "Installment delete success");
        } catch (\Exception $exception) {
            DB::rollBack();
            return redirect()->back()->withErrors("Installment delete failed");
        }
    }
    public function print_installment($installment_uid){
        $installment = Installment::with(['transaction','customer'])->where(['installment_uid' => $installment_uid])->first();
        return view("installment.print",['installment'=>$installment]);
    }
}

resources/views/installment/edit_installment.blade.php
@extends('layouts.master')
@section('style')
    <link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('plugins/flatpickr/flatpickr.css')}}">
@endsection
@section('heading')
    <h3>নতুন আমানত/ কিস্তি যুক্ত  করুন </h3>
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('home')}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
            </a>
        </li>
        <li class="breadcrumb-item"><a href="javascript:void(0);">আমানত/ কিস্তি </a></li>
        <li class="breadcrumb-item active" aria-current="page"><span>নতুন আমানত/ কিস্তি </span></li>
    </ol>
@endsection
@section('content')
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-12 layout-spacing">
            <div class="widget-content-area br-4">
                <form action="{{route('installment.edit',$installment->installment_uid)}}" method="post">
                    @csrf
                    <div class="form-row mb-4">
                        <div class="form-group col-md-6 select2-customer mb-0">
                            <label for="customer_id">ব্যক্তির নাম</label>
                            <select name="customer_id" id="customer_id" class="form-control">
                                <option selected value="{{$installment->customer->id}}">{{$installment->customer->name}} ({{$installment->customer->phone}} )</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="taka">টাকার পরিমান</label>
                            <input name="taka" type="number" class="form-control" id="taka" value="{{$installment->taka}}" placeholder="৬০,০০০">
                        </div>
                    </div>
                    <div class="form-row mb-4">
                        <div class="form-group col-md-6 mb-0">
                            <label for="date">তারিখ</label>
                            <input value="{{$installment->date}}" name="date" id="date" class="form-control flatpickr flatpickr-input active" type="text" placeholder="তারিখ নির্বাচন করুন ..">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="note">নোট</label>
                            <input value="{{$installment->note}}"  name="note" type="text" class="form-control" id="note" placeholder="নোট">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary mt-3">তথ্য যুক্ত করুন</button>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('plugins/select2/select2.min.js')}}"></script>
    <script src="{{asset("plugins/flatpickr/flatpickr.js")}}"></script>
    <script>
        var f1 = flatpickr(document.getElementById('date'));
        $("#customer_id").select2({
            placeholder: "Select Customer",
            ajax: {
                url: '{{route('users.search')}}',
                dataType: 'json',
                data: function (params) {
                    // Query parameters will be ?search=[term]&type=public
                    return {
                        search: params.term,
                        type: "public"
                    };
                },
                processResults: function (response) {
                    return {
                        results: $.map(response.data, function (txt, val) {
                            return {id: txt.id, text: txt.name}
                        })
                    };
                }
                // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
            }
        });
    </script>
@endsection

resources/views/installment/installments.blade.php
@extends("layouts.master")
@section("style")
    <link rel="stylesheet" type="text/css" href="{{asset('plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset("plugins/table/datatable/custom_dt_html5.css")}}">
    <link rel="stylesheet" type="text/css" href="{{asset("plugins/table/datatable/dt-global_style.css")}}">
@endsection
@section('heading')
    <h3>সকল কিস্তির হিসাব-নিকাশে তালিকা তথ্য</h3>
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg></a></li>
        <li class="breadcrumb-item"><a href="{{route('installment.add')}}">আমানত/ কিস্তি</a></li>
        <li class="breadcrumb-item active" aria-current="page"><span>আমানত/ কিস্তি লিস্ট</span></li>
    </ol>
@endsection
@section('content')
    <div class="row">

        <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
            <div class="widget-content widget-content-area br-6">
                <div class="table-responsive mb-4 mt-4">
                    {{$dataTable->table(['class'=>"table table-hover non-hover","style"=>"width:100%"])}}
                </div>
            </div>
        </div>
    </div>
@endsection
@section("script")

    <!-- BEGIN PAGE LEVEL CUSTOM SCRIPTS -->
    <script src="{{asset('plugins/table/datatable/datatables.js')}}"></script>
    <!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
    <script src="{{asset('plugins/table/datatable/button-ext/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/jszip.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/buttons.html5.min.js')}}"></script>
    <script src="{{asset('plugins/table/datatable/button-ext/buttons.print.min.js')}}"></script>
    {{$dataTable->scripts()}}
    </script>
@endsection

resources/views/installment/new_installment.blade.php
@extends('layouts.master')
@section('style')
    <link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('plugins/flatpickr/flatpickr.css')}}">
@endsection
@section('heading')
    <h3>নতুন আমানত/ কিস্তি যুক্ত  করুন </h3>
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('home')}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
            </a>
        </li>
        <li class="breadcrumb-item"><a href="javascript:void(0);">আমানত/ কিস্তি </a></li>
        <li class="breadcrumb-item active" aria-current="page"><span>নতুন আমানত/ কিস্তি </span></li>
    </ol>
@endsection
@section('content')
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-12 layout-spacing">
            <div class="widget-content-area br-4">
                <form action="{{route('installment.add')}}" method="post">
                    @csrf
                    <div class="form-row mb-4">
                        <div class="form-group col-md-6 select2-customer mb-0">
                            <label for="customer_id">ব্যক্তির নাম</label>
                            <select name="customer_id" id="customer_id" class="form-control">
                                <option selected>ব্যক্তির নাম নির্বাচন করুন</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="taka">টাকার পরিমান</label>
                            <input name="taka" type="number" class="form-control" id="taka" placeholder="৬০,০০০">
                        </div>
                    </div>
                    <div class="form-row mb-4">
                        <div class="form-group col-md-6 mb-0">
                            <label for="date">তারিখ</label>
                            <input value="{{date('Y-m-d')}}" name="date" id="date" class="form-control flatpickr flatpickr-input active" type="text" placeholder="তারিখ নির্বাচন করুন ..">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="note">নোট</label>
                            <input  name="note" type="text" class="form-control" id="note" placeholder="নোট">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary mt-3">তথ্য যুক্ত করুন</button>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('plugins/select2/select2.min.js')}}"></script>
    <script src="{{asset("plugins/flatpickr/flatpickr.js")}}"></script>
    <script>
        var f1 = flatpickr(document.getElementById('date'));
        $("#customer_id").select2({
            placeholder: "Select Customer",
            ajax: {
                url: '{{route('users.search')}}',
                dataType: 'json',
                data: function (params) {
                    // Query parameters will be ?search=[term]&type=public
                    return {
                        search: params.term,
                        type: "public"
                    };
                },
                processResults: function (response) {
                    return {
                        results: $.map(response.data, function (txt, val) {
                            return {id: txt.id, text: txt.name}
                        })
                    };
                }
                // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
            }
        });
    </script>
@endsection

resources/views/installment/print.blade.php
@extends('layouts.invoice')

@section('customer_section')
    <p class="inv-customer-name">{{$installment->customer->name}}</p>
    <p class="inv-customer-name">{{$installment->customer->company}}</p>
    <p class="inv-street-addr">{{$installment->customer->address}}</p>
@endsection
@section("invoice_head")
    ভাউচার
@endsection
@section('invoice_no')
    {{banglaNumber($installment->id)}}{{banglaNumber($installment->customer->id)}}{{banglaNumber(date('md',strtotime($installment->created_at)))}}
@endsection

@section('invoice_date')
    {{banglaNumber($installment->date)}}
@endsection

@section('content')
    <table class="table">
        <thead class="">
        <tr>
            <th class="text-left" scope="col">ক্রঃ নং</th>
            <th class="text-center" scope="col">বিবরণ</th>
            <th class="text-right" scope="col">টাকার পরিমান</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="text-left">{{banglaNumber(1)}}</td>
            <td class="text-center">{{$installment->note}}</td>
            <td class="text-right">{{en2bnNumber($installment->taka)}}</td>
        </tr>
        </tbody>
    </table>
@endsection
@section('content_footer')
    <div class="row">
        <div class="col-sm-8 col-7 grand-total-title">
            <h5 class="">সর্বমোট আমানত: </h5>
        </div>
        <div class="col-sm-4 col-5 grand-total-amount">
            <h5 class="">{{en2bnNumber($installment->taka)}} টাকা</h5>
        </div>
    </div>
@endsection